adminpanel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import LoginView, Dashboard, UserManagementView, ServiceProviderManagementView, SubAdminManagement, \
    CategoryView, OrderManagementView, VerificationManagementView, WorkerManagementView, OfferManagementView, \
    FinanceManagementView, StaticContentManagementView, NotificationManagementView, AdminProfileView, \
    ChangePasswordView, UserDetailView, ServiceProviderDetailView, SubAdminDetail, EditSubAdmin, AddServiceProvider, \
    CategoryDetail, AddCategoryView, SubCategoryView, SubCategoryDetail, AddSubCategory, AddSubAdmin, \
    AddServices, ServicesList, UpdateService, TopServicesView, TopServicesList, DeleteTopService, AssignServiceProvider, \
    SendQuoteView, RejectedOrderView, OfferDetailView, DeleteOfferView, UpdateOfferView, AddOffers, NotificationCount, \
    ReadNotificationView, InquiryView, UserProviderRegistrations, OrderDetail, UpdateContactUs, UpdateAboutUs, \
    UpdateTermsAndCondition, UpdatePrivacyPolicy, UnBlockUser, BlockUser, BlockServiceProvider, UnBlockServiceProvider, \
    DeleteSubAdmin, UpdateCategoryView, UpdateSubCategory, GetCategoryServiceProvider, CompletedOrders, \
    StaticPrivacyPolicyForAppStores, TermsAndConditionForAppStores, GetGstView, UpdateGstView, \
    ServiceProviderPasswordView, UserCsvView, OrderCsvView, ServiceProviderCsvView, CancelOrderView, HideCategory, \
    UnHideCategory, UpdateOrder, OrderCanceledByAdmin

app_name = 'adminpanel'

urlpatterns = [
                  path('login/', LoginView.as_view(), name='login'),
                  path('dashboard/', Dashboard.as_view(), name='dashboard'),
                  path('user-management/', UserManagementView.as_view(), name='user-management'),
                  path('service-provider-management/', ServiceProviderManagementView.as_view(),
                       name='service-provider-management'),
                  path('sub-admin-management/', SubAdminManagement.as_view(), name='sub-admin-management'),
                  path('add-category/', AddCategoryView.as_view(), name='add-category'),
                  path('category-management/', CategoryView.as_view(), name='category-management'),
                  path('category-detail/<int:pk>/', CategoryDetail.as_view(), name='category-detail'),
                  path('hide-category/<int:pk>/', HideCategory.as_view(), name='hide-category'),
                  path('unhide-category/<int:pk>/', UnHideCategory.as_view(), name='unhide-category'),
                  path('update-category/<int:pk>/', UpdateCategoryView.as_view(), name='update-category'),
                  path('order-management/', OrderManagementView.as_view(), name='order-management'),
                  path('complete-orders/', CompletedOrders.as_view(), name='complete-orders'),
                  path('order-detail/<int:pk>/', OrderDetail.as_view(), name='order-detail'),
                  path('rejected-order-management/', RejectedOrderView.as_view(), name='rejected-order-management'),
                  path('canceled-orders/', OrderCanceledByAdmin.as_view(), name='canceled-orders'),
                  path('verification-management/', VerificationManagementView.as_view(),
                       name='verification-management'),
                  path('worker-management/', WorkerManagementView.as_view(), name='worker-management'),
                  path('add-offer/', AddOffers.as_view(), name='add-offer'),
                  path('offer-management/', OfferManagementView.as_view(), name='offer-management'),
                  path('offer-detail/<int:pk>/', OfferDetailView.as_view(), name='offer-detail'),
                  path('offer-delete/<int:pk>/', DeleteOfferView.as_view(), name='offer-delete'),
                  path('update-offer/<int:pk>/', UpdateOfferView.as_view(), name='update-offer'),
                  path('finance-management/', FinanceManagementView.as_view(), name='finance-management'),
                  path('static-management/', StaticContentManagementView.as_view(), name='static-management'),
                  path('notification-management/', NotificationManagementView.as_view(),
                       name='notification-management'),
                  path('admin-profile/', AdminProfileView.as_view(), name='admin-profile'),
                  path('change-password/', ChangePasswordView.as_view(), name='change-password'),
                  path('user-detail/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
                  path('service-provider-detail/<int:pk>/', ServiceProviderDetailView.as_view(),
                       name='service-provider-detail'),
                  path('sub-admin-detail/<int:pk>/', SubAdminDetail.as_view(), name='sub-admin-detail'),
                  path('edit-sub-admin-detail/<int:pk>/', EditSubAdmin.as_view(), name='edit-sub-admin-detail'),
                  path('add-service-provider/', AddServiceProvider.as_view(), name='add-service-provider'),
                  path('add-sub-category/', AddSubCategory.as_view(), name='add-sub-category'),
                  path('sub-category-management/', SubCategoryView.as_view(), name='sub-category-management'),
                  path('service-provider-category/', GetCategoryServiceProvider.as_view(),
                       name='service-provider-category'),
                  path('sub-category-detail/<int:pk>/', SubCategoryDetail.as_view(), name='sub-category-detail'),
                  path('update-sub-category/<int:pk>/', UpdateSubCategory.as_view(), name='update-sub-category'),
                  path('add-sub-admin/', AddSubAdmin.as_view(), name='add-sub-admin'),
                  path('add-services/', AddServices.as_view(), name='add-services'),
                  path('services-list/', ServicesList.as_view(), name='services-list'),
                  path('update-service/<int:pk>/', UpdateService.as_view(), name='update-service'),
                  path('top-services/', TopServicesView.as_view(), name='top-services'),
                  path('top-services-list/', TopServicesList.as_view(), name='top-services-list'),
                  path('delete-top-service/<int:pk>/', DeleteTopService.as_view(), name='delete-top-service'),
                  path('assign-service-provider/', AssignServiceProvider.as_view(), name='assign-service-provider'),
                  path('send-quote/', SendQuoteView.as_view(), name='send-quote'),
                  path('cancel-order/', CancelOrderView.as_view(), name='cancel-order'),
                  path('notification-count/', NotificationCount.as_view(), name='notification-count'),
                  path('read-notification/', ReadNotificationView.as_view(), name='read-notification'),
                  path('inquiry/', InquiryView.as_view(), name='inquiry'),
                  path('privacy-policy-for-app-stores/', StaticPrivacyPolicyForAppStores.as_view(),
                       name='privacy-policy-for-app-stores'),
                  path('terms-and-condition-for-app-stores/', TermsAndConditionForAppStores.as_view(),
                       name='terms-and-condition-for-app-stores'),
                  path('update-contact-us/<int:pk>/', UpdateContactUs.as_view(), name='update-contact-us'),
                  path('update-about-us/<int:pk>/', UpdateAboutUs.as_view(), name='update-about-us'),
                  path('update-privacy-policy/<int:pk>/', UpdatePrivacyPolicy.as_view(), name='update-privacy-policy'),
                  path('unblock-user/<int:pk>/', UnBlockUser.as_view(), name='unblock-user'),
                  path('block-user/<int:pk>/', BlockUser.as_view(), name='block-user'),
                  path('block-service-provider/<int:pk>/', BlockServiceProvider.as_view(),
                       name='block-service-provider'),
                  path('unblock-service-provider/<int:pk>/', UnBlockServiceProvider.as_view(),
                       name='unblock-service-provider'),
                  path('delete-sub-admin/<int:pk>/', DeleteSubAdmin.as_view(), name='delete-sub-admin'),
                  path('update-gst/<int:pk>/', UpdateGstView.as_view(), name='update-gst'),
                  path('update-terms-and-condition/<int:pk>/', UpdateTermsAndCondition.as_view(),
                       name='update-terms-and-condition'),
                  path('user-provider-registration/', UserProviderRegistrations.as_view(),
                       name='user-provider-registration'),
                  path('get-gst/', GetGstView.as_view(), name='get-gst'),
                  path('service-provider-password/<int:pk>/', ServiceProviderPasswordView.as_view(),
                       name='service-provider-password'),
                  path('user-csv/', UserCsvView.as_view(), name='user-csv'),
                  path('bookings-csv/', OrderCsvView.as_view(), name='bookings-csv'),
                  path('service-provider-csv/', ServiceProviderCsvView.as_view(), name='service-provider-csv'),
                  path('edit-order/<int:pk>/', UpdateOrder.as_view(), name='edit-order'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

khalian/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from adminpanel.views import PasswordResetConfirmView, PasswordResetView, PasswordChangeView, PasswordChangeDoneView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminpanel/', include('adminpanel.urls', namespace='adminpanel')),
    path('', include('website.urls', namespace='website')),
    path('api/', include('src.urls', namespace='api')),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('password-reset/',
         PasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('password-reset-done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password_reset_done.html'
         ),
         name='password_reset_done'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('change-password/', PasswordChangeView.as_view(template_name='changePassword.html'),
         name='change_password'),
    path('password-change-done/',
         PasswordChangeDoneView.as_view(template_name='change_password_done.html'),
         name='password_change_done'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

src/urls.py
from .views import CreateUser, LoginView, CheckUserExists, UpdateUserProfile, GetUserProfilePic, UpdateUserLanguage, \
    HomeView, SearchingServices, SaveSearchesHistory, GetUserPastSearches, BookingView, GetBookingDetail, ContactUsView, \
    PrivacyPolicyView, TermsAndConditionView, AboutUsView, GeneralInquiryView, LogoutView, UpcomingBooking, PastBooking, \
    OnGoingBooking, UpdateOrderStatus, RatingAndReviews, GetServiceReviewRatings, GetDefaultOfferPercentView, \
    GetAllOffersAndDiscount, GetUserDetail, NotificationList, GetUserNotificationCount, UpdateNotification, \
    GetSubCategory, GetServices, GetServiceDetail, GetUsersBooking, InquiryView, GetServiceName, ServiceProviderLogin, \
    ForgetPassword, ServiceProviderLogoutView, ServiceProviderDashboard, NewRequestView, NewBookingRequestDetail, \
    UpdateBookingByServiceProvider, ServiceProviderCompletedTasks, ServiceProviderOnGoingTasks, ProviderRegisterView, \
    CouponList, ApplyCoupon, RemoveCoupoun, GuestUserToken, AcceptOrderServiceProviderView, \
    RejectOrderServiceProviderView, CheckNumberOfBookings, GetGstValue
from django.urls import path
from rest_framework.schemas import get_schema_view

app_name = 'src'

urlpatterns = [
    path('user-create/', CreateUser.as_view(), name='user-create'),
    path('user-login/', LoginView.as_view(), name='user-login'),
    path('check-user-exists/', CheckUserExists.as_view(), name='check-user-exists'),
    path('update-user-profile-pic/', UpdateUserProfile.as_view(), name='update-user-profile-pic'),
    path('get-user-profile-pic/', GetUserProfilePic.as_view(), name='get-user-profile-pic'),
    path('update-user-language/', UpdateUserLanguage.as_view(), name='update-user-language'),
    path('home-api/', HomeView.as_view(), name='home-api'),
    path('search-services/', SearchingServices.as_view(), name='search-services'),
    path('save-search/', SaveSearchesHistory.as_view(), name='save-search'),
    path('get-saved-searches/', GetUserPastSearches.as_view(), name='get-saved-searches'),
    path('book-service/', BookingView.as_view(), name='book-service'),
    path('upcoming-bookings/', UpcomingBooking.as_view(), name='upcoming-bookings'),
    path('past-bookings/', PastBooking.as_view(), name='past-bookings'),
    path('ongoing-bookings/', OnGoingBooking.as_view(), name='ongoing-bookings'),
    path('booking-detail/', GetBookingDetail.as_view(), name='booking-detail'),
    path('contact-us/', ContactUsView.as_view(), name='contact-us'),
    path('privacy-policy/', PrivacyPolicyView.as_view(), name='privacy-policy'),
    path('terms-and-condition/', TermsAndConditionView.as_view(), name='terms-and-condition'),
    path('about-us/', AboutUsView.as_view(), name='about-us'),
    path('help-with-order/', GeneralInquiryView.as_view(), name='help-with-order'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('update-order/', UpdateOrderStatus.as_view(), name='update-order'),
    path('ratings-and-review/', RatingAndReviews.as_view(), name='ratings-and-review'),
    path('service-ratings-and-review/', GetServiceReviewRatings.as_view(), name='service-ratings-and-review'),
    path('get-default-discount-percent/', GetDefaultOfferPercentView.as_view(), name='get-default-discount-percent'),
    path('get-all-offers/', GetAllOffersAndDiscount.as_view(), name='get-all-offers'),
    path('get-user-detail/', GetUserDetail.as_view(), name='get-user-detail'),
    path('get-user-notification-list/', NotificationList.as_view(), name='get-user-notification-list'),
    path('get-user-notification-count/', GetUserNotificationCount.as_view(), name='get-user-notification-count'),
    path('update-user-notification/', UpdateNotification.as_view(), name='update-user-notification'),
    path('get-subcategories/', GetSubCategory.as_view(), name='get-subcategories'),
    path('get-services/', GetServices.as_view(), name='get-services'),
    path('get-service-detail/', GetServiceDetail.as_view(), name='get-service-detail'),
    path('get-users-bookings-ids/', GetUsersBooking.as_view(), name='get-users-bookings-ids'),
    path('general-inquiry/', InquiryView.as_view(), name='general-inquiry'),
    path('services/', GetServiceName.as_view(), name='services'),
    path('service-provider-login/', ServiceProviderLogin.as_view(), name='service-provider-login'),
    path('forget-password/', ForgetPassword.as_view(), name='forget-password'),
    path('service-provider-logout/', ServiceProviderLogoutView.as_view(), name='service-provider-logout'),
    path('service-provider-dashboard/', ServiceProviderDashboard.as_view(), name='service-provider-dashboard'),
    path('new-booking-requests/', NewRequestView.as_view(), name='new-booking-requests'),
    path('new-booking-request-detail/', NewBookingRequestDetail.as_view(), name='new-booking-request-detail'),
    path('update-booking-status-by-service-provider/', UpdateBookingByServiceProvider.as_view(),
         name='update-booking-status-by-service-provider'),
    path('service-provider-completed-tasks/', ServiceProviderCompletedTasks.as_view(),
         name='service-provider-completed-tasks'),
    path('service-provider-on-going-tasks/', ServiceProviderOnGoingTasks.as_view(),
         name='service-on-going-completed-tasks'),
    path('provider-register-from-user-app/', ProviderRegisterView.as_view(), name='provider-register-from-user-app'),
    path('accept-order-service-provider/', AcceptOrderServiceProviderView.as_view(),
         name='accept-order-service-provider'),
    path('reject-order-service-provider/', RejectOrderServiceProviderView.as_view(),
         name='reject-order-service-provider'),
    path('coupon-list/', CouponList.as_view(), name='coupon-list'),
    path('check-number-of-bookings/', CheckNumberOfBookings.as_view(), name='check-number-of-bookings'),
    path('apply-coupon/', ApplyCoupon.as_view(), name='apply-coupon'),
    path('guest-user/', GuestUserToken.as_view(), name='guest-user'),
    path('remove-coupon/', RemoveCoupoun.as_view(), name='remove-coupon'),
    path('get-gst-value/', GetGstValue.as_view(), name='get-gst-value'),
]

# schema_view = get_schema_view(
#     title='Server Monitoring API',
#     url='http://127.0.0.1:8000/api/',
#     patterns=urlpatterns,
# )

adminpanel/templates/add-admin.html
{% extends 'base.html' %}
{% block body %}
<section class="demandRight boxs">
    <div class="content-wrapper">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="demandInner boxs">
        <h2 class="main">Add SubAdmin
        </h2>

        <div class="formDett padding-25 bgWhite">
            <form method="post">
                {% csrf_token %}
                <div class="row">

                    <div class="col-sm-6">
                        <div class="form-group formGroup">
                            <label for="" class="labelel"></label>
                            <input type="text" class="form-control formControl" name="full_name" required
                                   placeholder="Name">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group formGroup newSelect">
                            <!--                            <label for="" class="labelel"></label>-->
                            <!--                            <input type="text" class="form-control formControl" name="can_manage_dashboard" required placeholder="UserId">-->
                            <select class="mySelect for" multiple="multiple" name="access_rights"
                                    style="width: 100%"></select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group formGroup">
                            <label for="" class="labelel"></label>
                            <input type="email" class="form-control formControl" name="email" required
                                   placeholder="Email">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group formGroup">
                            <label for="" class="labelel"></label>
                            <input type="number" class="form-control formControl" name="phone_number" required
                                   placeholder="Phone Number">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group formGroup">
                            <label for="" class="labelel"></label>
                            <input type="password" class="form-control formControl" name="password" required
                                   placeholder="Password">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group formGroup">
                            <label for="" class="labelel"></label>
                            <input type="password" class="form-control formControl" name="confirm_password"
                                   placeholder="Confirm Password">
                        </div>
                    </div>

                    <div class="CommonBtn CommonBtn2 boxs">
                        <button class="btns" type="submit">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
<script>
var data = ["Can Manage User", "Can Manage Order", "Can Manage Provider", "Can Manage Category", "Can Manage Sub Category","Can Manage Services","Can Manage Subadmin","Can Manage Top Services","Can Manage Coupons"];
var placeholder = "select";
$(".mySelect").select2({
data: data,
placeholder: placeholder,
allowClear: false,
minimumResultsForSearch: 5
});



</script>
<script>
    $('select').selectpicker();



</script>
{% endblock body %}

adminpanel/templates/categoryDetails.html
{% extends 'base.html' %}
{% block body %}
<section class="demandRight boxs">
    <div class="demandInner boxs">
        <h2 class="main">Category Details</h2>
        <div class="userDetails bgWhite padding-25">

            <ul class="detailsUser padding-left-25">
                <li><span class="first">Category Id</span>{{object.id}}</li>
                <li><span class="first">Category Name</span>{{object.category_name}}</li>
                <li><span class="first">Category Name Arabic</span>{{object.category_name_arabic}}</li>
                {% if object.category_image %}
                <li><span class="first">Category Image</span><img src="{{object.category_image.url}}" class="imgWidths"></li>
                {% else %}
                <li><span class="first">Category Image</span></li>
                {% endif %}
            </ul>

        </div>
    </div>
</section>
{% endblock body %}

adminpanel/templates/delete-offer.html
{% extends 'base.html' %}
{% block body %}
<section class="demandRight boxs">
    <div class="content-wrapper">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="demandInner boxs">
        <h2 class="main">Add Service</h2>
        <div class="formDett padding-25 bgWhite">
            <div class="row">

                <div class="col-sm-8">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group formGroup">
                            <label for="" class="labelel"></label>
                            <h2>Are you sure you want to remove this coupon ?</h2><br>
                            <button type="submit" class="fa fa-check fa-2x">Yes</button>&nbsp;&nbsp;&nbsp;&nbsp;
                            <a class="fa fa-close fa-2x" href="{% url 'adminpanel:top-services-list'  %}">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock body %}

adminpanel/templates/order-detail.html
{% extends 'base.html' %}
{% block body %}
<section class="demandRight boxs">
    <div class="demandInner boxs">
        <h2 class="main">Category Details</h2>
        <div class="userDetails bgWhite padding-25">

            <ul class="detailsUser padding-left-25">
                <li><span class="first">Order Id</span>{{object.id}}</li>
                <li><span class="first">Order Date</span>{{object.date}}</li>
                <li><span class="first">Order Time</span>{{object.time}}</li>
                <li><span class="first">User ID</span>{{object.user.id}}</li>
                <li><span class="first">Customer Name</span>{{object.user.full_name}}</li>
                <li><span class="first">Customer Contact Number</span>{{object.user.user.country_code}}{{object.user.user.phone_number}}</li>
                <li><span class="first">Order Address</span>{{object.address}}</li>
                <li><span class="first">Service Name</span>{{object.service.service_name}}</li>
                <li><span class="first">Requirement</span>{{object.requirement}}</li>
                {% if object.image_1 %}
                <li><span class="first">Image1</span>
                    <figure style="200px;"><img src="{{object.image_1.url}}" class ="imgWidths" style="width:100%;"></figure>
                </li>
                {% else %}
                <li><span class="first">Image1</span></li>
                {% endif %}
                {% if object.image_2 %}
                <li><span class="first">Image2</span>
                    <figure style="200px;"><img src="{{object.image_2.url}}" class ="imgWidths" style="width:100%;"></figure>
                </li>
                {% else %}
                <li><span class="first">Image2</span></li>
                {% endif %}
            </ul>

        </div>
    </div>
</section>
{% endblock body %}

adminpanel/templates/password-management.html
{% extends 'base.html' %}
{% block body %}
<section class="demandRight boxs">
        <div class="content-wrapper">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="demandInner boxs">
        <div class="AddService">
            <h2 class="main">Change Password for user {{provider_name}}
            </h2>
            <div class="boxs padding-25 bgWhite">
                <div class="row">
                    {% if form.errors %}
                    {% for field in form %}
                    {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="col-sm-12">
                            <div class="form-group formGroup">
                                <label for="" class="labelel"></label>
                                <input type="password" class="form-control formControl" name="new_password1"
                                       placeholder="New Password">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group formGroup">
                                <label for="" class="labelel"></label>
                                <input type="password" class="form-control formControl" name="new_password2"
                                       placeholder="Confirm Password">
                            </div>
                        </div>
                        <div class="CommonBtn CommonBtn2 boxs">
                            <button class="btns" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</section>
{% endblock body %}

adminpanel/templates/password_reset_confirm.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ondemand | Login</title>
    <!-- Bootstrap -->
    <link href="{% static 'img/fav.png' %}" rel="icon" type="icon/image">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
    <!-- <link href="css/reset.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
<section class="login boxs">
    <div class="loginInner">
        <div class="logo">
            <img src="{% static 'img/logo.png' %}" alt="logo" class="img-fluid">
        </div>
        <br>
        <div class="logoContent">
            <div class="content-wrapper">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
                {% endif %}
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="form-group formGroup">
                    <label for="" class="labelel"></label>
                    <input class="form-control" type="password" placeholder="New Password"
                           name="new_password1" required
                           id="id_new_password1">
                </div>
                <div class="form-group formGroup">
                    <label for="" class="labelel"></label>
                    <input class="form-control" type="password"
                           placeholder="Confirm Password" name="new_password2" required
                           id="id_new_password2"><br>
                </div>
                <button type="submit" class="btn btn-primary btn-lg">Reset Password</button>
            </form>
        </div>
    </div>
</section>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
</body>

</html>

adminpanel/templates/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% trans "Thank you for using our site!" %}

{% blocktrans %}The Fatortech team {% endblocktrans %}

{% endautoescape %}